[package]
name = "sqlcipher-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusqlite = { version = "0.27.0", features = ["bundled-sqlcipher-vendored-openssl"] }
tss-esapi = "7.0.1"
